spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disertatie
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
#logging:
#  level:
#    org.springframework.web: DEBUG
server:
  port: 9000
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data

EventController:
  addEvent: Add a specific event
  applyOnEvent: Apply as user for an event

EventLocationController:
  addEventLocation: Add a specific location for an event
  deleteEventLocation: Delete a specific event

EventReservationController:
  addEventReservation: Reserve a place to event
  deleteEventReservation: Delete a specific reservation